### ISSUE TITLE
backend 1번째 업무

### ISSUE THREAD

**Issue by igiza1213** [SRHS-SPAM/SRH-Community-Web#14]
간단한 로그인기능을 구현해 볼것이에요 최종적으로 우리 홈페이지에 쓸것인것이에요 백엔드팀 모여서 논의도해보고 같이 공부하는 첫번째 일인것이에요
기한은 없는것이에요

**Comment by igiza1213** [comment]
쿠키 저장
id입력할 칸
pw입력할 칸
데이터 저장
정보 판단
기능 등이 필요할듯

**Comment by NANONANDFLASH** [comment]
헉

**Comment by dnjeh** [comment]
백엔드(공부를사유삼아안함)
